coverage:
  status:
    project:
      default:
        target: auto
    patch:
      default:
        target: auto

fixes:
  - "app/build/intermediates/javac/debug/classes/::"
  - "app/src/main/java/::"