coverage:
  status:
    project:
      default:
        target: auto
    patch:
      default:
        target: auto

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false

fixes:
  - "::app/src/main/java/"
